//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public System.DateTime ThoiGian { get; set; }
        public int MaNV { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public double SoGioTangCa { get; set; }
    
        public virtual TRANGTHAICHAMCONG TRANGTHAICHAMCONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
