//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_TRINHDO
    {
        public int MaNV_TD { get; set; }
        public int MaTrinhDo { get; set; }
        public int MaNV { get; set; }
        public string DonViCap { get; set; }
    
        public virtual TRINHDO TRINHDO { get; set; }
    }
}
