//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BAOHIEMs = new HashSet<BAOHIEM>();
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public int MaNV { get; set; }
        public string HoLot { get; set; }
        public string Ten { get; set; }
        public string CMND { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public byte[] HinhAnh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public bool DaThoiViec { get; set; }
        public Nullable<int> MaBP { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaTrinhDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHIEM> BAOHIEMs { get; set; }
        public virtual BOPHAN BOPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
    }
}
