//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUONG
    {
        public int MaTienThuong { get; set; }
        public string TenTienThuong { get; set; }
        public Nullable<System.DateTime> ThoiGianApDung { get; set; }
        public Nullable<int> SoTien { get; set; }
    }
}
