//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAUTRU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHAUTRU()
        {
            this.NHANVIEN_KHAUTRU = new HashSet<NHANVIEN_KHAUTRU>();
        }
    
        public int MaKT { get; set; }
        public string TenLoaiKhauTru { get; set; }
        public Nullable<int> HeSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_KHAUTRU> NHANVIEN_KHAUTRU { get; set; }
    }
}
