//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITRINHDO
    {
        public int MaLoaiTrinhDo { get; set; }
        public string TenTrinhDo { get; set; }
        public string a { get; set; }
    }
}
