//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_KHAUTRU
    {
        public int MaNV_KT { get; set; }
        public Nullable<System.DateTime> NgayKhauTru { get; set; }
        public Nullable<int> HeSo { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaKT { get; set; }
    
        public virtual KHAUTRU KHAUTRU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
