//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_NGHIPHEP
    {
        public int MaNgayNghi { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<bool> DaPheDuyet { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
