//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_TRINHDO
    {
        public int MaNV_TD { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaTrinhDo { get; set; }
        public Nullable<double> PhuCapTrinhDo { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
    }
}
