//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_PHUCAP
    {
        public int MaNV_PC { get; set; }
        public int MaNV { get; set; }
        public int MaPhuCap { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<decimal> Tien { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHUCAP PHUCAP { get; set; }
    }
}
