//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRINHDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRINHDO()
        {
            this.NHANVIEN_TRINHDO = new HashSet<NHANVIEN_TRINHDO>();
        }
    
        public int MaTrinhDo { get; set; }
        public string TenTrinhDo { get; set; }
        public string NgayApDung { get; set; }
        public Nullable<double> PhuCapTrinhDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_TRINHDO> NHANVIEN_TRINHDO { get; set; }
    }
}
